### ISSUE TITLE
The message queue is not in assigned list

### ISSUE THREAD

**Issue by andyyumiao** [apache/rocketmq-flink#107]
I got the error when i consume rocketmq message in flink job：

 ```
   Caused by: org.apache.rocketmq.client.exception.MQClientException: The message queue is not in assigned list, message queue: MessageQueue [topic=yumiao1205, brokerName=broker-a, queueId=1]
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
```

My rocketmq version: 5.1.1
flink version: 1.15.0

**Comment by cj495840252** [comment]
I also encounter this error， it's seem that still not solved

**Comment by cj495840252** [comment]
I am still have this error
while i run the simpleConsumer it's working normally, it's mean can connect rocketmq?
![image](https://github.com/apache/rocketmq-flink/assets/63491689/141bb5c8-feea-4d1d-83ed-cb7e5951c7ca)

it's still failed while I run the ConnectorExample 
RocketMQ: 5.0.0

```
2024-03-12 23:05:42  WARN [   Source: Custom Source (1/2)#0] [e.flink.runtime.taskmanager.Task] Source: Custom Source (1/2)#0 (ea15ccd58a1ef50baebef0860ee2e52b) switched from INITIALIZING to FAILED with failure cause: org.apache.rocketmq.client.exception.MQClientException: The message queue is not in assigned list, message queue: MessageQueue [topic=test, brokerName=broker-a, queueId=1]
For more information, please visit the url, https://rocketmq.apache.org/docs/bestPractice/06FAQ
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.seek(DefaultLitePullConsumerImpl.java:660)
	at org.apache.rocketmq.client.impl.consumer.DefaultLitePullConsumerImpl.seekToEnd(DefaultLitePullConsumerImpl.java:693)
	at org.apache.rocketmq.client.consumer.DefaultLitePullConsumer.seekToEnd(DefaultLitePullConsumer.java:394)
	at org.apache.flink.connector.rocketmq.legacy.RocketMQSourceFunction.initOffsets(RocketMQSourceFunction.java:394)
	at org.apache.flink.connector.rocketmq.legacy.RocketMQSourceFunction.open(RocketMQSourceFunction.java:246)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:100)
	at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:107)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreGates(StreamTask.java:700)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.call(StreamTaskActionExecutor.java:100)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:676)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:643)
	at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:948)
	at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:917)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:741)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:563)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by cj495840252** [comment]
> See #96
hi, good morning , this is my setting
![image](https://github.com/apache/rocketmq-flink/assets/63491689/1a13e90f-7e8a-49d2-a7be-ee69bc64356f)

**Comment by madi1819** [comment]
I have also encountered this problem. Has it been resolved
![image](https://github.com/apache/rocketmq-flink/assets/44694741/da1eedb6-3e35-424e-85f0-9d4ce6ba325b)

**Comment by madi1819** [comment]
> See #96

this is my test code
![image](https://github.com/apache/rocketmq-flink/assets/44694741/fea5d008-77d5-4675-a1b9-129813840c1f)

**Comment by loserwang1024** [comment]
> See #96
It seems do nothing!

**Comment by ping-cai** [comment]
it seens do nothing! this brantch 'main-latest' still exist! who can help fix this problem
RocketMQ Version:4.9.2
Flink Version: 1.15.2
problem details:
Caused by: org.apache.rocketmq.client.exception.MQClientException: The message queue is not in assigned list, message queue: MessageQueue [topic=tp_ld_driver_behavior_score_change, brokerName=broker-onlinemq1-d, queueId=0]
For more information, please visit the url, http://rocketmq.apache.org/docs/faq/
I guess this issue comes from the class 'DefaultLitePullConsumer',Previously, it was DefaultMQPullConsumer，This class will be removed in 2022, and a better implementation {@link DefaultLitePullConsumer} is recommend to use

**Comment by liangjw** [comment]
Is this bug fixed? I have encountered this issue and found the messagequeue shoud be assigned. But I cant find any assined code.

The following code is runnable if assign the queue to consumer manually:

`        Collection<MessageQueue> totalQueues = consumer.fetchMessageQueues(topic);
        consumer.assign(totalQueues);

        consumer.seekToEnd(totalQueues.iterator().next());`
